"""
DTAC-IR Database Models
All SQLAlchemy ORM models — one file per domain entity.
"""
from datetime import datetime
from enum import Enum as PyEnum
from sqlalchemy import (
    Column, Integer, String, Float, Boolean, DateTime,
    Enum, Text, ForeignKey, Index
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.core.database import Base


# ── Enums ────────────────────────────────────────────────────────────────────────

class SeverityLevel(str, PyEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

class AlertStatus(str, PyEnum):
    OPEN = "open"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"

class DeviceStatus(str, PyEnum):
    TRUSTED = "trusted"
    SUSPICIOUS = "suspicious"
    QUARANTINED = "quarantined"
    BLOCKED = "blocked"

class AttackType(str, PyEnum):
    PORT_SCAN = "port_scan"
    SYN_FLOOD = "syn_flood"
    DNS_EXFILTRATION = "dns_exfiltration"
    BRUTE_FORCE = "brute_force"
    ARP_SPOOFING = "arp_spoofing"
    ANOMALY = "anomaly"
    NORMAL = "normal"
    # Added to match the Phase 2 ML model's actual output classes
    # (BENIGN, BOTNET, DOS, WEB_ATTACK) — these previously had no matching
    # DB enum value and were being lossily collapsed into ANOMALY/NORMAL.
    BOTNET = "botnet"
    DOS = "dos"
    WEB_ATTACK = "web_attack"


# ── Models ───────────────────────────────────────────────────────────────────────

class Device(Base):
    """
    Represents a network device being monitored.
    Trust score is the core of our DTAC (Dynamic Trust Assessment & Control).
    """
    __tablename__ = "devices"

    id = Column(Integer, primary_key=True, index=True)
    ip_address = Column(String(45), unique=True, index=True, nullable=False)
    mac_address = Column(String(17), nullable=True)
    hostname = Column(String(255), nullable=True)
    trust_score = Column(Float, default=100.0, nullable=False)
    status = Column(Enum(DeviceStatus), default=DeviceStatus.TRUSTED, nullable=False)
    first_seen = Column(DateTime(timezone=True), server_default=func.now())
    last_seen = Column(DateTime(timezone=True), onupdate=func.now(), server_default=func.now())
    is_blocked = Column(Boolean, default=False)
    total_packets = Column(Integer, default=0)
    total_alerts = Column(Integer, default=0)

    alerts = relationship("Alert", back_populates="device", lazy="dynamic")
    incidents = relationship("Incident", back_populates="device", lazy="dynamic")

    __table_args__ = (
        Index("idx_device_trust_status", "trust_score", "status"),
    )

    def __repr__(self):
        return f"<Device ip={self.ip_address} trust={self.trust_score:.1f} status={self.status}>"


class PacketLog(Base):
    """
    Stores processed packet feature vectors — NOT raw packets (too large).
    These are the features fed to the ML model.
    """
    __tablename__ = "packet_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    src_ip = Column(String(45), index=True, nullable=False)
    dst_ip = Column(String(45), nullable=False)
    src_port = Column(Integer, nullable=True)
    dst_port = Column(Integer, nullable=True)
    protocol = Column(String(10), nullable=False)
    packet_length = Column(Integer, nullable=False)
    flags = Column(String(20), nullable=True)       # TCP flags: SYN, ACK, FIN, etc.
    ttl = Column(Integer, nullable=True)
    payload_size = Column(Integer, default=0)
    predicted_class = Column(Enum(AttackType), default=AttackType.NORMAL)
    ml_confidence = Column(Float, default=0.0)
    is_threat = Column(Boolean, default=False)

    __table_args__ = (
        Index("idx_packet_timestamp_src", "timestamp", "src_ip"),
        Index("idx_packet_threat", "is_threat", "timestamp"),
    )


class Alert(Base):
    """
    Security alert generated by detection engine or ML model.
    """
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), server_default=func.now())
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    severity = Column(Enum(SeverityLevel), nullable=False, index=True)
    status = Column(Enum(AlertStatus), default=AlertStatus.OPEN, index=True)
    attack_type = Column(Enum(AttackType), nullable=False)
    src_ip = Column(String(45), nullable=False)
    dst_ip = Column(String(45), nullable=True)
    dst_port = Column(Integer, nullable=True)
    ml_confidence = Column(Float, nullable=True)
    rule_triggered = Column(String(100), nullable=True)   # Which rule fired (if rule-based)
    device_id = Column(Integer, ForeignKey("devices.id"), nullable=True)
    incident_id = Column(Integer, ForeignKey("incidents.id"), nullable=True)
    is_acknowledged = Column(Boolean, default=False)
    acknowledged_by = Column(String(100), nullable=True)

    device = relationship("Device", back_populates="alerts")
    incident = relationship("Incident", back_populates="alerts")

    __table_args__ = (
        Index("idx_alert_severity_status", "severity", "status"),
    )


class Incident(Base):
    """
    Groups related alerts into a trackable incident.
    Mirrors how real SOC teams work (MITRE ATT&CK campaign tracking).
    """
    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), server_default=func.now())
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    severity = Column(Enum(SeverityLevel), nullable=False)
    status = Column(Enum(AlertStatus), default=AlertStatus.OPEN)
    device_id = Column(Integer, ForeignKey("devices.id"), nullable=True)
    mitre_tactic = Column(String(100), nullable=True)     # e.g. "Reconnaissance"
    mitre_technique = Column(String(100), nullable=True)  # e.g. "T1046 - Port Scanning"
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    assigned_to = Column(String(100), nullable=True)

    device = relationship("Device", back_populates="incidents")
    alerts = relationship("Alert", back_populates="incident", lazy="dynamic")
